package com.github.cloudfoundry.community.console

import org.springframework.security.web.context.AbstractSecurityWebApplicationInitializer

class SpringSecurityBootstrap extends AbstractSecurityWebApplicationInitializer{
}
